# Rede DHCP
subnet 192.168.10.0 netmask 255.255.255.0 {

    # Faixa de endereços
    range 192.168.10.100 192.168.10.200;

    # Gateway
    option routers 192.168.10.1;

    # DNS
    option domain-name-servers 192.168.10.1;

    # Tempo padrão da concessão
    default-lease-time 600;

    # Tempo máximo da concessão
    max-lease-time 7200;
}

# Reserva DHCP por MAC
host cliente-lab {

    # MAC do cliente
    hardware ethernet 08:00:27:d7:33:27;

    # IP reservado
    fixed-address 192.168.10.50;
}
